trigger:
- master
- feature/*
#put your variabe names 
variables:
 technology: 'ansible'
 armtemplate: 'Templates'
 sonaranaysis: 'false'
resources:
  repositories:
  - repository: Templates
    type: git
    name: Templates

#stages:
#- stage: javabuild
#  displayName: javabuild
#  jobs:
#   - job: test
#     pool:
#      vmImage: 'ubuntu-latest'
#     steps:
#      - task: CmdLine@2
#        inputs:
#          script: 'ansible-galaxy install --force --roles-path="roles/" --role-file="roles/requirements.yml"'
#        displayName: 'test'

stages:
- stage: javabuild
  displayName: javabuild
  jobs:
  - template: javabuild.yaml@Templates
  condition: eq('${{ variables.technology }}', 'java')
- stage: springbootbuild
  displayName: springbootbuild
  jobs:
  - template: springbootbuild.yaml@Templates
  condition: eq('${{ variables.technology }}', 'springboot')
- stage: ansible
  displayName: ansiblebuild
  jobs:
  - template: ansiblebuild.yml@Templates
  condition: eq('${{ variables.technology }}', 'ansible2')
- stage: armtemplate
  displayName: armtemplatebuild
  jobs:
  - template: ansiblebuild.yml@Templates
  condition: eq('${{ variables.armtemplate }}', 'Templates')
