---
- name: Create a resource group
  hosts: localhost
  connection: local
  tasks:
   - name: create reosurce group
     azure_rm_resourcegroup:
       name: myAKSRG
       location: westeu
       tags:
        purpose: aks
        delete: never
